version: '3.8'

services:
  eureka-server:
    build: ../eureka-server
    ports:
      - "8761:8761"
    networks:
      - nttdata-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  api-gateway:
    build: ../api-gateway
    ports:
      - "8700:8700"
    depends_on:
      eureka-server:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - nttdata-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8700/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  product-service:
    build: ../product-service
    ports:
      - "8100:8100"
    depends_on:
      api-gateway:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - nttdata-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8100/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  order-service:
    build: ../order-service
    ports:
      - "8200:8200"
    depends_on:
      api-gateway:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - nttdata-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8200/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - nttdata-network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - nttdata-network

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - nttdata-network

networks:
  nttdata-network:
    driver: bridge